version: '3.8'

services:

  # Deine eigene Anwendung
  myhelloworldapp:
    build:
      context: .

  # Webserver-Service mit Nginx
  webserver:
    image: nginx:latest
    ports:
      - "8085:80"

  someapps:
    image: alpine
